### ISSUE TITLE
I just installed, but how can I use it?

### ISSUE THREAD

**Issue by nelson6e65** [pinguinjkeke/php-class-tree#2]
I don't see in Packages menu. :confused:

**Comment by pinguinjkeke** [comment]
I'll add the package menu item in next release.
Now you can use it from Atom commands menu.

Thank you for your response

**Comment by nelson6e65** [comment]
Oh. Thanks. :+1: 

PD: Maybe should be great to have it in a right sidebar.

**Comment by pinguinjkeke** [comment]
I have added checkbox into settings for right position, menu items and hotkeys in v1.0.0
