### ISSUE TITLE
Not Displaying Consistently

### ISSUE THREAD

**Issue by donCarlosOne** [pinguinjkeke/php-class-tree#7]
I can't seem to get this to load/display consistently.  In fact, I've only ever seen it displayed one time, after installing some other packages, however since reloading Atom, cannot get it to display again.  When it was displayed it would not scroll, so a lot of my classes were unavailable to me through the tree - but it did work well for the classes that were displayed.

**Comment by pinguinjkeke** [comment]
Call "Php Class Tree: Build" through command pallet first.
I'll check the scroll. Never used PHP files with 10+ classes

**Comment by donCarlosOne** [comment]
Tried your suggestion to run Php Class Tree: Build, and not only does the it display, but the scrolling now works.

**Comment by pinguinjkeke** [comment]
Thank you for reply, but the package still needs auto activation.
